// Generated by CoffeeScript 1.4.0
(function() {
  var socket, storage;

  socket = io.connect('http://localhost:8080');

  window.storage = storage = {};

  socket.emit('requestData', 'username');

  socket.on('sendData', function(data) {
    storage.Settings = data.Settings;
    storage.List = data.List;
    return storage.Task = data.Task;
  });

  window.addTask = function(id, name, list) {
    var index;
    if (list == null) {
      list = "inbox";
    }
    index = storage.Task.push({
      name: name,
      completed: false,
      priority: 1,
      list: list,
      id: id
    });
    return socket.emit('create', ["task", storage.Task[index - 1]]);
  };

  window.updateTask = function(id, attr, val) {
    var task, _i, _len, _ref;
    _ref = storage.Task;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      task = _ref[_i];
      if (task.id === id) {
        break;
      }
    }
    task[attr] = val;
    return socket.emit('update', ["task", id, attr, val]);
  };

  window.destroyTask = function(id) {
    var index, task, _i, _len, _ref;
    _ref = storage.Task;
    for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
      task = _ref[index];
      if (task.id === id) {
        break;
      }
    }
    storage.Task.splice(index, 1);
    return socket.emit('destroy', ["task", id]);
  };

}).call(this);
